Frontend:
  impl: GEM5
  clock_ratio: 1
  num_expected_insts: 500000

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 2

  DRAM:
    impl: GDDR6A
    org:
      preset: GDDR6_16Gb_x16
      channel_width: 16
    timing:
      preset: GDDR6_14000_1250mV_quad 
    drampower_enable: true
    voltage:
      preset: Default
    current: 
      preset: Default

  Controller:
    impl: GenericA
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
    wr_low_watermark: 0.3
    wr_high_watermark: 0.7
    plugins:

  AddrMapper:
    impl: RoBgBaRaChCo
